name: Vault example 1 - Retrieve secrets from Vault

on:
  workflow_dispatch:

jobs:
  fetch-secrets:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Retrieve secrets from Vault
        id: vault-secrets
        uses: hashicorp/vault-action@v3.4.0
        with:
          url: ${{ secrets.VAULT_ADDR }}
          token: ${{ secrets.VAULT_TOKEN }}
          secrets: |
            secret/data/ci/aws accessKey2 | AWS_ACCESS_KEY_ID ;
            secret/data/ci/aws secretKey2 | AWS_SECRET_ACCESS_KEY ;
            secret/data/ci npm_token2 | NPM_TOKEN;
            secret/data/blah blahblah | BLAH_BLAH;

      - name: Use the secrets in deployment
        run: |
          # Example: Run a command using secrets
          echo "Deploying with access key ID (masked): $AWS_ACCESS_KEY_ID"
          # The actual values are masked in logs for security
          
      - name: Configure AWS credentials (example)
        env:
          AWS_ACCESS_KEY_ID: ${{ env.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY }}
        run: |
          # Your deployment commands here
          echo "AWS credentials configured"
